import uuid
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field


class Scale(BaseModel):
    """Structured operational and volumetric scale specification.
    Fields MUST be None if not explicitly supplied or strictly inferable.
    """
    expected_concurrent_users: Optional[int] = Field(
        None,
        description="Peak or sustained concurrent active users. Must be null if unspecified.",
    )
    expected_total_users: Optional[int] = Field(
        None,
        description="Total registered user base. Must be null if unspecified.",
    )
    expected_requests_per_second: Optional[int] = Field(
        None,
        description="Peak or sustained request throughput (RPS). Must be null if unspecified.",
    )
    expected_storage: Optional[str] = Field(
        None,
        description="Total expected data volume or storage capacity (e.g., '10 TB'). Must be null if unspecified.",
    )
    geographic_scope: Optional[str] = Field(
        None,
        description="Target geographical footprint (e.g., 'Global', 'North America', 'Single Region'). Must be null if unspecified.",
    )


class RequirementAnalysis(BaseModel):
    """Structured engineering requirement analysis output generated by Requirement Engine."""
    domain: str = Field(
        ...,
        description="Industry or application domain (e.g., 'food_delivery', 'fintech', 'e_commerce', 'transportation', 'media_streaming', 'education', 'healthcare', or 'unknown').",
    )
    system_type: str = Field(
        ...,
        description="Broad architecture archetype (e.g., 'web_application', 'mobile_application', 'api_platform', 'real_time_system', 'data_platform', 'distributed_system', 'desktop_application', 'embedded_system', or 'unknown').",
    )
    scale: Scale = Field(
        default_factory=Scale,
        description="Explicit or strictly validated scale parameters.",
    )
    functional_requirements: List[str] = Field(
        default_factory=list,
        description="Core functional capabilities the system must provide (e.g., 'user authentication', 'order processing').",
    )
    non_functional_requirements: List[str] = Field(
        default_factory=list,
        description="System qualities and architectural characteristics (e.g., 'high availability', 'low latency', 'security', 'scalability').",
    )
    constraints: List[str] = Field(
        default_factory=list,
        description="Explicit technical, organizational, or compliance constraints provided by the user (e.g., 'Azure cloud', 'GDPR compliance').",
    )
    priorities: List[str] = Field(
        default_factory=list,
        description="Key architectural trade-off priorities (e.g., 'scalability', 'consistency', 'cost-efficiency', 'security').",
    )
    external_integrations: List[str] = Field(
        default_factory=list,
        description="External third-party systems or APIs mentioned or required (e.g., 'payment gateway', 'SMS provider').",
    )
    data_requirements: List[str] = Field(
        default_factory=list,
        description="Data characteristics, retention, or consistency requirements.",
    )
    assumptions: List[str] = Field(
        default_factory=list,
        description="Explicitly identified operational assumptions (strictly avoiding unverified tech stack choices).",
    )
    ambiguities: List[str] = Field(
        default_factory=list,
        description="Vague or unquantified statements requiring architectural clarification (e.g., 'Expected scale is unspecified for scalable claim').",
    )
    missing_information: List[str] = Field(
        default_factory=list,
        description="Critical engineering variables missing from the input (e.g., 'latency SLA', 'expected traffic volume', 'budget').",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 reflecting specification completeness and clarity.",
    )

    model_config = ConfigDict(from_attributes=True)


class RequirementAnalysisResponse(BaseModel):
    """API response schema wrapping the RequirementAnalysis with entity metadata."""
    project_id: uuid.UUID
    analysis_id: uuid.UUID
    version: int
    analysis: RequirementAnalysis
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class RequirementAnalysisListResponse(BaseModel):
    """API response schema for listing historical requirement analyses."""
    project_id: uuid.UUID
    items: List[RequirementAnalysisResponse]
    total: int
