import uuid
from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field


class AgentDecision(BaseModel):
    """Specific technical choice and architectural rationale."""
    decision: str = Field(
        ...,
        description="Architecture or design dimension (e.g., 'Database Paradigm', 'Authentication Protocol').",
        examples=["Database Paradigm"],
    )
    choice: str = Field(
        ...,
        description="Selected technology, pattern, or approach.",
        examples=["PostgreSQL (Relational/ACID)"],
    )
    reason: str = Field(
        ...,
        description="Engineering justification based strictly on the structured requirement.",
        examples=["ACID transactional guarantees required for order and financial records."],
    )


class AgentRisk(BaseModel):
    """Identified architectural, security, or performance vulnerability/risk."""
    title: str = Field(..., description="Short summary of the risk.")
    severity: str = Field(
        ...,
        description="Risk severity level ('low', 'medium', 'high', 'critical').",
        examples=["high"],
    )
    mitigation: str = Field(..., description="Recommended mitigation strategy.")


class AgentComponent(BaseModel):
    """Core structural component proposed by the agent."""
    name: str = Field(..., description="Component name.")
    type: str = Field(
        ...,
        description="Component archetype (e.g., 'service', 'database', 'cache', 'gateway', 'queue', 'idp').",
    )
    description: str = Field(..., description="Role and responsibility within the architecture.")
    technology: Optional[str] = Field(None, description="Proposed specific technology or standard.")


class AgentConnection(BaseModel):
    """Inter-component communication link."""
    from_component: str = Field(..., description="Source component.")
    to_component: str = Field(..., description="Target component.")
    protocol: str = Field(..., description="Communication protocol (e.g., 'HTTPS/REST', 'gRPC', 'AMQP', 'TCP').")
    description: Optional[str] = Field(None, description="Nature of the interaction.")


class AgentOutput(BaseModel):
    """Unified structured evaluation generated by an AI Agent."""
    agent_type: str = Field(
        ...,
        description="Agent specialization identifier ('architecture', 'security', 'performance').",
    )
    summary: str = Field(..., description="Executive architectural evaluation summary.")
    recommendations: List[str] = Field(
        default_factory=list,
        description="Key tactical recommendations proposed by this agent.",
    )
    decisions: List[AgentDecision] = Field(
        default_factory=list,
        description="Concrete architectural or operational decisions.",
    )
    risks: List[AgentRisk] = Field(
        default_factory=list,
        description="Identified risks, trade-offs, and threat vectors.",
    )
    components: List[AgentComponent] = Field(
        default_factory=list,
        description="Structural building blocks recommended by this agent.",
    )
    connections: List[AgentConnection] = Field(
        default_factory=list,
        description="Inter-service protocols and communication topology.",
    )

    model_config = ConfigDict(from_attributes=True)


class AgentRunRecordResponse(BaseModel):
    """API response representing a single agent execution record."""
    id: uuid.UUID
    project_id: uuid.UUID
    requirement_analysis_id: uuid.UUID
    agent_type: str
    status: str
    output: Optional[AgentOutput] = None
    error_message: Optional[str] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ProjectAgentResultsResponse(BaseModel):
    """Consolidated response providing latest outputs from all three AI agents."""
    project_id: uuid.UUID
    requirement_analysis_id: Optional[uuid.UUID] = None
    status: str = Field(
        ...,
        description="Overall review readiness ('ready', 'partial', 'not_run', 'failed').",
    )
    architecture: Optional[AgentOutput] = None
    security: Optional[AgentOutput] = None
    performance: Optional[AgentOutput] = None
    created_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)
